---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: image-server
  template:
    metadata:
      labels:
        name: image-server
    spec:
      containers:
      - name: application
        image: e770r/gopher-gallery-image-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
        - name: "LINKS_SERVER"
          value: "http://links-server:9000"

--- 
apiVersion: v1 
kind: Service
metadata:
  name: image-server
  labels:
    app: image-server
spec:
  type: ClusterIP
  selector:
    app: image-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http


            
