apiVersion: apps/v1
kind: Deployment
metadata:
  name: links-db
  labels:
    app: links-db
spec:
  selector:
    matchLabels:
      app: links-db
  replicas: 1
  template:
    metadata:
      labels:
        app: links-db
    spec:
      containers:
      - name: links-db
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: links-db
  labels:
    app: links-db
spec:
  type: ClusterIP
  selector:
    app: links-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379