---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: links-store
spec:
  replicas: 2
  selector:
    matchLabels:
      name: links-store
  template:
    metadata:
      labels:
        name: links-store
    spec:
      containers:
      - name: application
        image: e770r/gopher-gallery-links-store:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        env:
        - name: "REDIS_HOST"
          value: "links-db"
          
        - name: "REDIS_PORT"
          value: "6379"

--- 
apiVersion: v1 
kind: Service
metadata:
  name: links-store
  labels:
    app: links-store
spec:
  type: ClusterIP
  selector:
    app: links-store
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http


            
