name: publish_images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Build and push gallery
        uses: docker/build-push-action@v2
        with:
          context: ./../../gallery
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            e770r/gopher-gallery:latest
      -
        name: Build and image-server
        uses: docker/build-push-action@v2
        with:
          context: ./../../image-server
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            e770r/gopher-gallery-image-server:latest
      -
        name: Build and links-store
        uses: docker/build-push-action@v2
        with:
          context: ./../links-store
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            e770r/gopher-gallery-links-store:latest